[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.15.0" }
serde = "1.0"
borsh = { version = "0.10.3", default-features = false }
hex = "0.4"
