[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
zk-sdk = { path = "../zk-sdk" }
methods = { path = "../methods" }
risc0-zkvm = { version = "0.15.0" }
serde = { version = "1.0", default-features = false }
borsh = { version = "0.10.3", default-features = false }
hex = "0.4"